name: BuildOnWindows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Setup Conan
        run: |
          python3 -m pip install conan
      - name: Build
        run: |
          mkdir build
          cd build
          conan install .. -s build_type=Release -s compiler="Visual Studio" -s compiler.runtime=MT
          conan build -bf . -sf .. ..
          dir
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: abc-${{ steps.git_describe.outputs.value }}
          path: build/abc.exe
